<?php
namespace ChatPilot\Core;

// Prevent direct file access.
if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Class Lifecycle
 * Manages plugin activation, deactivation, and compatibility diagnostics.
 */
class Lifecycle {

	/**
	 * Main activation routine.
	 * Triggered on register_activation_hook.
	 */
	public static function activate() {
		// 1. Compatibility Check.
		self::verify_compatibility();

		// 2. Initialize database schema.
		$schema = new \ChatPilot\Database\Schema();
		$schema->create_tables();

		// 3. Setup default settings repository configurations.
		$repository = new \ChatPilot\Settings\Repository();
		$repository->initialize_defaults();

		// Reset provider status to "Not Yet Verified" or "Not Configured" on activation.
		$openai_key = $repository->get( 'providers.openai.api_key', '' );
		$gemini_key = $repository->get( 'providers.gemini.api_key', '' );

		$repository->set( 'providers.openai.status', empty( $openai_key ) ? 'Not Configured' : 'Not Yet Verified' );
		$repository->set( 'providers.gemini.status', empty( $gemini_key ) ? 'Not Configured' : 'Not Yet Verified' );

		// Reset dynamic runtime state elements to prevent stale info.
		$repository->set( 'providers.openai.response_time', 0.0 );
		$repository->set( 'providers.openai.error_count', 0 );
		$repository->set( 'providers.openai.last_success', '' );
		$repository->set( 'providers.openai.last_failure', '' );

		$repository->set( 'providers.gemini.response_time', 0.0 );
		$repository->set( 'providers.gemini.error_count', 0 );
		$repository->set( 'providers.gemini.last_success', '' );
		$repository->set( 'providers.gemini.last_failure', '' );

		$repository->save();

		// 4. Flush rewrites.
		flush_rewrite_rules();
	}

	/**
	 * Main deactivation routine.
	 * Triggered on register_deactivation_hook.
	 */
	public static function deactivate() {
		// 1. Clear transients generated by the plugin.
		delete_transient( 'chat_pilot_system_status' );

		// 2. Flush rewrites to leave rewrite rules clean.
		flush_rewrite_rules();
	}

	/**
	 * Verifies environment complies with minimum requirements.
	 * Triggers failure error page if check fails.
	 */
	private static function verify_compatibility() {
		// Minimum PHP requirement.
		$min_php = '7.4';
		if ( version_compare( PHP_VERSION, $min_php, '<' ) ) {
			deactivate_plugins( CHAT_PILOT_BASENAME );
			wp_die(
				/* translators: %s: minimum PHP version */
				sprintf( esc_html__( 'Chat Pilot requires PHP version %s or greater to run. Your current version is %s. Please contact your host to request an upgrade.', 'chat-pilot' ), esc_html( $min_php ), esc_html( PHP_VERSION ) ),
				esc_html__( 'Plugin Activation Error', 'chat-pilot' ),
				array( 'back_link' => true )
			);
		}

		// Minimum WordPress requirement.
		$min_wp = '6.0';
		global $wp_version;
		if ( version_compare( $wp_version, $min_wp, '<' ) ) {
			deactivate_plugins( CHAT_PILOT_BASENAME );
			wp_die(
				/* translators: %s: minimum WordPress version */
				sprintf( esc_html__( 'Chat Pilot requires WordPress version %s or greater. Your current installation is version %s. Please upgrade WordPress to activate the plugin.', 'chat-pilot' ), esc_html( $min_wp ), esc_html( $wp_version ) ),
				esc_html__( 'Plugin Activation Error', 'chat-pilot' ),
				array( 'back_link' => true )
			);
		}
	}
}
